// @seeker-dm/core — confidential messaging protocol.
//
// The cryptographic heart of the app: dedicated messaging identities, stealth
// one-time addresses, view-key scanning, and end-to-end encryption. Pure and
// self-contained — only Node's built-in `crypto` (X25519 ECDH + HKDF +
// AES-256-GCM). No network, no chain, no wallet here.
//
// Trust model: confidentiality is FROM third parties (the relay, chain
// analysts, network observers), NOT from your conversation partner — the
// recipient is meant to learn who messaged them (that's inside the encrypted
// payload, for replies). See ../../SECURITY.md for the full threat model and
// the items flagged for audit (notably: binding on-curve *spend authority* to
// the stealth address is future work — v1 treats the one-time address as
// recipient-controlled).

import crypto from "node:crypto";

const b64u = b => Buffer.from(b).toString("base64url");
const unb64u = s => Buffer.from(s, "base64url");

function genKeypair() {
  const { publicKey, privateKey } = crypto.generateKeyPairSync("x25519");
  return { pub: unb64u(publicKey.export({ format: "jwk" }).x), priv: unb64u(privateKey.export({ format: "jwk" }).d) };
}
const pubKeyObj = pubRaw => crypto.createPublicKey({ key: { kty: "OKP", crv: "X25519", x: b64u(pubRaw) }, format: "jwk" });
const privKeyObj = (privRaw, pubRaw) =>
  crypto.createPrivateKey({ key: { kty: "OKP", crv: "X25519", x: b64u(pubRaw), d: b64u(privRaw) }, format: "jwk" });
const ecdh = (myPriv, myPub, peerPub) => crypto.diffieHellman({ privateKey: privKeyObj(myPriv, myPub), publicKey: pubKeyObj(peerPub) });
const hkdf = (shared, info, len = 32) => Buffer.from(crypto.hkdfSync("sha256", shared, Buffer.alloc(0), Buffer.from(info), len));

/* ---------- identity ---------- */

// Dual-key stealth identity: a view key (scans incoming) + a spend key (would
// authorize moving anything received). This is a DEDICATED messaging identity,
// generated by the app — never the user's funded wallet.
export function createIdentity() {
  return { view: genKeypair(), spend: genKeypair() };
}
export function metaAddress(id) {
  return b64u(Buffer.concat([id.view.pub, id.spend.pub]));
}
export function parseMetaAddress(s) {
  const raw = unb64u(s);
  if (raw.length !== 64) throw new Error("bad meta-address");
  return { viewPub: raw.subarray(0, 32), spendPub: raw.subarray(32, 64) };
}

// Serialize a full identity (incl. private keys) for on-device secure storage.
// NEVER leaves the device unencrypted; store under the OS keystore / Seed Vault.
export function exportIdentity(id) {
  return b64u(Buffer.concat([id.view.pub, id.view.priv, id.spend.pub, id.spend.priv]));
}
export function importIdentity(s) {
  const r = unb64u(s);
  if (r.length !== 128) throw new Error("bad identity blob");
  return {
    view: { pub: r.subarray(0, 32), priv: r.subarray(32, 64) },
    spend: { pub: r.subarray(64, 96), priv: r.subarray(96, 128) },
  };
}

/* ---------- seal (sender) ---------- */

// Build a sealed note bound to a fresh one-time stealth address. The output is
// what goes to the relay; it identifies neither sender nor recipient. `viewTag`
// is a 1-byte client-side scan optimization (skips full derivation on ~255/256
// of non-matching notes). `rng` is injectable for tests.
export function sealNote(recipientMetaAddr, plaintext, rng = crypto.randomBytes) {
  const { viewPub, spendPub } = parseMetaAddress(recipientMetaAddr);
  const eph = genKeypair(); // fresh per note → unlinkable
  const shared = ecdh(eph.priv, eph.pub, viewPub);
  const stealth = crypto.createHash("sha256").update(hkdf(shared, "stealth")).update(spendPub).digest();
  const key = hkdf(shared, "encrypt", 32);
  const iv = rng(12);
  const cipher = crypto.createCipheriv("aes-256-gcm", key, iv);
  const ct = Buffer.concat([cipher.update(Buffer.from(plaintext, "utf8")), cipher.final()]);
  return {
    v: 1,
    viewTag: hkdf(shared, "viewtag", 1).toString("hex"),
    ephemeralPub: b64u(eph.pub),
    stealthAddress: b64u(stealth),
    nonce: b64u(iv),
    ciphertext: b64u(Buffer.concat([ct, cipher.getAuthTag()])),
  };
}

/* ---------- scan (recipient) ---------- */

// Check one note with the view key. Returns { isMine, plaintext?, tampered? }.
// Only the holder of the view private key can recompute the shared secret;
// knowing someone's public meta-address is not enough to detect their notes.
export function scanNote(identity, note) {
  const shared = ecdh(identity.view.priv, identity.view.pub, unb64u(note.ephemeralPub));
  if (note.viewTag && hkdf(shared, "viewtag", 1).toString("hex") !== note.viewTag) return { isMine: false };

  const expected = crypto.createHash("sha256").update(hkdf(shared, "stealth")).update(identity.spend.pub).digest();
  if (b64u(expected) !== note.stealthAddress) return { isMine: false };

  const key = hkdf(shared, "encrypt", 32);
  const data = unb64u(note.ciphertext);
  const dec = crypto.createDecipheriv("aes-256-gcm", key, unb64u(note.nonce));
  dec.setAuthTag(data.subarray(data.length - 16));
  try {
    const plaintext = Buffer.concat([dec.update(data.subarray(0, data.length - 16)), dec.final()]).toString("utf8");
    return { isMine: true, plaintext, stealthAddress: note.stealthAddress };
  } catch {
    return { isMine: true, tampered: true, stealthAddress: note.stealthAddress };
  }
}
